name: "publish package to npm"

on:
  push:
    branches:
      - main  # specify the branch you want to deploy from
    paths-ignore:
      - 'package.json'  # ignore this file to prevent recursive triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # Do not persist the default credentials

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Configure Git for pushing
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.ACTION_TOKEN }}@github.com/arjangimahdi/phetch-cli.git
          git config --global user.name "arjangimahdi"
          git config --global user.email "github.mahdiarjangi.official@gmail.com"

      - name: Check for GitHub Actions Bot Commit
        id: check_bot
        run: |
          LAST_COMMITTER=$(git log -1 --pretty=format:'%an')
          if [[ "$LAST_COMMITTER" == "github-actions[bot]" ]]; then
            echo "::set-output name=skip_publish::true"
          else
            echo "::set-output name=skip_publish::false"
          fi

      - name: bump version
        if: steps.check_bot.outputs.skip_publish == 'false'
        run: |
          npm version patch -m "CI: Bump version to %s"
          git push origin HEAD  # Push changes using the manually configured Git

      - name: publish
        if: steps.check_bot.outputs.skip_publish == 'false'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMTOKEN }}
